"""Add trend_scores table

Revision ID: 05b983977d7a
Revises: a85606d479bb
Create Date: 2026-09-18 20:11:24.165612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b983977d7a'
down_revision: Union[str, None] = 'a85606d479bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_scores',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('view_velocity', sa.Float(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('signal_snapshot', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_scores_score'), 'trend_scores', ['score'], unique=False)
    op.create_index(op.f('ix_trend_scores_source_id'), 'trend_scores', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('trend_scores')
