"""Initial schema

Revision ID: a85606d479bb
Revises: 
Create Date: 2026-09-18 19:25:21.678735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85606d479bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('previous_state', sa.String(length=100), nullable=True),
    sa.Column('new_state', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('agent_run_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_job_id'), 'audit_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('channels',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('sources',
    sa.Column('channel_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('workflow_state', sa.Enum('DISCOVERED', 'RIGHTS_PENDING', 'RIGHTS_APPROVED', 'RIGHTS_BLOCKED', 'TRANSCRIBING', 'TRANSCRIBED', 'CLIP_ANALYSIS', 'CLIPS_READY', 'SCRIPT_READY', 'VIDEO_RENDERING', 'RENDERED', 'QC_PENDING', 'QC_PASSED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'READY_TO_PUBLISH', 'UPLOADING', 'PUBLISHED', 'FAILED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('source_class', sa.Enum('USER_OWNED', 'COMMERCIAL_LICENSE', 'CREATIVE_COMMONS', 'PERMISSION_BASED', 'UNKNOWN', name='sourceclass'), nullable=False),
    sa.Column('license_type', sa.Enum('OWNED', 'COMMERCIAL', 'CC_BY', 'CC_BY_SA', 'CC_BY_NC', 'CC_BY_ND', 'CC0', 'STANDARD_YOUTUBE', 'UNKNOWN', name='licensetype'), nullable=False),
    sa.Column('rights_status', sa.Enum('APPROVED', 'CONDITIONAL', 'REVIEW_REQUIRED', 'BLOCKED', name='rightsstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_channel_id'), 'sources', ['channel_id'], unique=False)
    op.create_index(op.f('ix_sources_external_id'), 'sources', ['external_id'], unique=True)
    op.create_index(op.f('ix_sources_published_at'), 'sources', ['published_at'], unique=False)
    op.create_index(op.f('ix_sources_rights_status'), 'sources', ['rights_status'], unique=False)
    op.create_index(op.f('ix_sources_views'), 'sources', ['views'], unique=False)
    op.create_index(op.f('ix_sources_workflow_state'), 'sources', ['workflow_state'], unique=False)
    op.create_table('clip_candidates',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('payoff', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_candidates_source_id'), 'clip_candidates', ['source_id'], unique=False)
    op.create_table('projects',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('state', sa.Enum('DISCOVERED', 'RIGHTS_PENDING', 'RIGHTS_APPROVED', 'RIGHTS_BLOCKED', 'TRANSCRIBING', 'TRANSCRIBED', 'CLIP_ANALYSIS', 'CLIPS_READY', 'SCRIPT_READY', 'VIDEO_RENDERING', 'RENDERED', 'QC_PENDING', 'QC_PASSED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'READY_TO_PUBLISH', 'UPLOADING', 'PUBLISHED', 'FAILED', 'ARCHIVED', name='workflowstate'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_source_id'), 'projects', ['source_id'], unique=False)
    op.create_index(op.f('ix_projects_state'), 'projects', ['state'], unique=False)
    op.create_table('rights_records',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_class', sa.Enum('USER_OWNED', 'COMMERCIAL_LICENSE', 'CREATIVE_COMMONS', 'PERMISSION_BASED', 'UNKNOWN', name='sourceclass'), nullable=False),
    sa.Column('license_type', sa.Enum('OWNED', 'COMMERCIAL', 'CC_BY', 'CC_BY_SA', 'CC_BY_NC', 'CC_BY_ND', 'CC0', 'STANDARD_YOUTUBE', 'UNKNOWN', name='licensetype'), nullable=False),
    sa.Column('commercial_use', sa.Boolean(), nullable=False),
    sa.Column('modification_allowed', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_reference', sa.String(length=1024), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=True),
    sa.Column('evidence_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'CONDITIONAL', 'REVIEW_REQUIRED', 'BLOCKED', name='rightsstatus'), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=50), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rights_records_source_id'), 'rights_records', ['source_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_source_id'), 'transcripts', ['source_id'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('license_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_table('clip_scores',
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('hook_score', sa.Float(), nullable=False),
    sa.Column('meaning_score', sa.Float(), nullable=False),
    sa.Column('standalone_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=False),
    sa.Column('retention_score', sa.Float(), nullable=False),
    sa.Column('visual_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_scores_clip_id'), 'clip_scores', ['clip_id'], unique=True)
    op.create_index(op.f('ix_clip_scores_final_score'), 'clip_scores', ['final_score'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.Enum('DISCOVERY_JOB', 'TRANSCRIPTION_JOB', 'CLIP_ANALYSIS_JOB', 'SCRIPT_GENERATION_JOB', 'VOICE_GENERATION_JOB', 'VIDEO_RENDER_JOB', 'QC_JOB', 'UPLOAD_JOB', 'ANALYTICS_JOB', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_payload', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('renders',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('video_path', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('caption_path', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_project_id'), 'renders', ['project_id'], unique=False)
    op.create_table('scripts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=True),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('payoff', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('full_script', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_clip_id'), 'scripts', ['clip_id'], unique=False)
    op.create_index(op.f('ix_scripts_project_id'), 'scripts', ['project_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('render_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('privacy_status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_jobs_render_id'), 'publishing_jobs', ['render_id'], unique=False)
    op.create_index(op.f('ix_publishing_jobs_status'), 'publishing_jobs', ['status'], unique=False)
    op.create_table('quality_checks',
    sa.Column('render_id', sa.String(length=36), nullable=False),
    sa.Column('audio_score', sa.Float(), nullable=False),
    sa.Column('caption_score', sa.Float(), nullable=False),
    sa.Column('visual_score', sa.Float(), nullable=False),
    sa.Column('content_score', sa.Float(), nullable=False),
    sa.Column('rights_score', sa.Float(), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['render_id'], ['renders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_checks_render_id'), 'quality_checks', ['render_id'], unique=False)
    op.create_table('published_videos',
    sa.Column('publishing_job_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publishing_job_id'], ['publishing_jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_videos_external_id'), 'published_videos', ['external_id'], unique=True)
    op.create_index(op.f('ix_published_videos_publishing_job_id'), 'published_videos', ['publishing_job_id'], unique=False)
    op.create_table('analytics',
    sa.Column('published_video_id', sa.String(length=36), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=False),
    sa.Column('comments', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('average_view_duration_seconds', sa.Float(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_video_id'], ['published_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_captured_at'), 'analytics', ['captured_at'], unique=False)
    op.create_index(op.f('ix_analytics_published_video_id'), 'analytics', ['published_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('analytics')
    op.drop_table('published_videos')
    op.drop_table('quality_checks')
    op.drop_table('publishing_jobs')
    op.drop_table('transcript_segments')
    op.drop_table('scripts')
    op.drop_table('renders')
    op.drop_table('jobs')
    op.drop_table('clip_scores')
    op.drop_table('assets')
    op.drop_table('transcripts')
    op.drop_table('rights_records')
    op.drop_table('projects')
    op.drop_table('clip_candidates')
    op.drop_table('sources')
    op.drop_table('users')
    op.drop_table('channels')
    op.drop_table('audit_events')

